// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/services": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/about" | "/contact" | "/services";
  };
  "../src/components/Home.jsx": {
    id: "../src/components/Home";
    page: "/";
  };
  "../src/components/About.jsx": {
    id: "../src/components/About";
    page: "/about";
  };
  "../src/components/Contact.jsx": {
    id: "../src/components/Contact";
    page: "/contact";
  };
  "../src/components/Services.jsx": {
    id: "../src/components/Services";
    page: "/services";
  };
};